### ISSUE TITLE
Add EFO import, specifying terms needed using efo_seed.txt

### ISSUE THREAD

**Issue by dosumis** [cellannotation/cap_ontology#1]
We currently load all of EFO, potentially bringing in axiomatization that can cause problems for other ontologies, including Uberon.  We should instead be using a small slice of the ontology, specified as a set IDs in a seed file.  (See other ODK repos for examples).

**Comment by ghost** [comment]
>  We should instead be using a small slice of the ontology,

@dosumis, do you have thoughts on what this should be? Perhaps terms under [assay](http://purl.obolibrary.org/obo/OBI_0000070)?

**Comment by dosumis** [comment]
That could work.  Or  the seed could just be terms currently allowed by CAP.  The import module generated will be larger than that.

**Comment by dosumis** [comment]
1. Add EFO to import to  [capo-odk.yaml](https://github.com/kharchenkolab/cap_ontology/edit/main/src/ontology/capo-odk.yaml)  Note - this may require specifying URL as EFO is not under obolibrary.
2. If possible, specify a very minimal import algo for import in [capo-odk.yaml](https://github.com/kharchenkolab/cap_ontology/edit/main/src/ontology/capo-odk.yaml)  - This may be possible with the key `filter` and value `MIREOT`.
3. Run update_my_repo goal with make.
4. Add a list of EFO IDs to https://github.com/kharchenkolab/cap_ontology/tree/main/src/ontology/imports/efo_terms.txt (this file will appear after update_my_repo goal is run on ODK).
5. Run a release of cap_ontology


Potentially useful reference docs:
https://oboacademy.github.io/obook/howto/update-import/
http://pato-ontology.github.io/pato/odk-workflows/RepoManagement/

**Comment by dosumis** [comment]
Once all this is done, switch pipeline config from EFO to capo.owl (using github raw link - https://raw.githubusercontent.com/kharchenkolab/cap_ontology/main/capo.owl)

**Comment by ghost** [comment]
@dosumis, Shawn has been helping with this and asked if the plan is to take the "base approach" for imports. Can you provide some insight on this?

**Comment by dosumis** [comment]
Imports from EFO should use the EFO-base file which can be found at: https://www.ebi.ac.uk/efo/efo-base.owl

(This doesn't really matter if we're only importing bare terms, but is safer for future use).

**Comment by dosumis** [comment]
Decision on import type - just import the bare terms.  No relationships.  This can be done with MIREOT.
