### ISSUE TITLE
Add terms for doublet and junk

### ISSUE THREAD

**Issue by dosumis** [cellannotation/cap_ontology#9]
These are needed for annotation of single cell data for cases where a row in a cell by gene table does not represent a cell but rather combined data about a pair of cells (doublet) or some other material (junk).

We should not spend much time trying to define clearly - these terms are internal to CAP and usage is driven by guidance on the CAP platform.

**Comment by ghost** [comment]
The following terms have been added to capo-edit.owl:

CAPO:1000000 doublet
CAPO:1000001 junk
